barbara-bouillicot/HobbyConnect

app/models/chatroom.rb, app/models/event.rb, app/models/hobby.rb, app/models/message.rb, app/models/request.rb, app/models/selected_hobby.rb, app/models/user.rb
=> associations and validations complete

db/seeds.rb
=> seeded with hobbies

app/views/users/show.html.erb
corrected calculation for user age
=> user age corrected

app/controllers/users_controller.rb, app/models/user.rb, app/views/users/show.html.erb
added events and hobbies on profile page and updated association on user.rb (has_many events) because it was missing
right now user doesn't have any hobbies
=> events and hobbies on profile shown

.gitignore, Gemfile, Gemfile.lock, app/assets/stylesheets/components/_icons.scss, app/assets/stylesheets/components/_index.scss, app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/models/hobby.rb, app/models/user.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/pages/home.html.erb, app/views/users/show.html.erb, config/environments/development.rb, config/storage.yml, db/migrate/20240319161049_create_active_storage_tables.active_storage.rb, db/schema.rb, db/seeds.rb
I've added the cloudinary feature and added the icons on the sign up/edit file and profile
=> cloudinary feature and icons

app/controllers/events_controller.rb, app/views/events/_new.html.erb, app/views/events/_show.html.erb, app/views/events/index.html.erb, app/views/users/show.html.erb, config/routes.rb, test/controllers/events_controller_test.rb
added event controller, index and modal for event details
=> added event controller

app/assets/stylesheets/components/_icons.scss, app/javascript/controllers/toggle_icons_controller.js, app/views/devise/registrations/new.html.erb, app/views/pages/home.html.erb, app/views/pages/profile.html.erb
Added the toggle icons stimulus for the sign-up page
=> stimulus toggle icons done

app/controllers/users_controller.rb, app/views/devise/registrations/new.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, config/environments/production.rb
=> sign up fix

app/assets/stylesheets/pages/_home.scss, app/views/chatrooms/index.html.erb, app/views/devise/sessions/new.html.erb, app/views/events/index.html.erb, app/views/hobbies/index.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, app/views/users/index.html.erb
=> testing out header font with blueberry style

app/views/users/show.html.erb
Now you can click only on the hobbies you have in common to ask for a match
=> matching feature improved

app/javascript/controllers/matching_modal_controller.js, app/views/chatrooms/_new.html.erb, app/views/users/show.html.erb
hobby icon added to the match request modal
=> hobby icon added to the match request modal

Gemfile, Gemfile.lock, app/views/shared/_navbar.html.erb, db/seeds.rb
Created new seeds for hobbies and users
=> created new seeds

app/controllers/events_controller.rb, app/models/event.rb, app/views/users/show.html.erb
=> fixed errors

app/javascript/controllers/edit_event_controller.js, app/views/events/_event_modal.html.erb
added request destroy action, when your request was accepted you can delete your request
=> added destroy action for requests

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_icons.scss, app/javascript/controllers/hobby_selection_controller.js, app/javascript/controllers/toggle_icons_controller.js, app/views/chatrooms/_new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb
added the feature to limit the selection of hobbies to 6
=> added the JS to select hobbies

app/assets/stylesheets/components/_chatroom.scss, app/views/chatrooms/index.html.erb, app/views/chatrooms/show.html.erb, app/views/messages/_message.html.erb
Fixed chatroom bug and customized the chatroom, still need to add the right colors
=> fixed chatroom and added style

app/controllers/events_controller.rb, app/javascript/controllers/add_event_controller.js, app/views/events/_new.html.erb, app/views/users/show.html.erb
fixed errors: see when inputs are filled wrong.
=> Fix add event errors1

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_hobby_show.scss, app/assets/stylesheets/components/_icons.scss, app/assets/stylesheets/pages/_home.scss, app/views/chatrooms/index.html.erb, app/views/devise/registrations/new.html.erb
=> fixed the double checkout

app/controllers/events_controller.rb
fixed add event again. Now it should work.. hopefully
=> fixed event issue, notice is there

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_chatroom.scss, app/assets/stylesheets/components/_header.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_searchbar.scss, app/assets/stylesheets/components/_user_card.scss, app/assets/stylesheets/pages/_home.scss, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/sessions/new.html.erb, app/views/hobbies/index.html.erb, app/views/layouts/application.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb
also made nav/header/button colors more blue than pink. styled the user cards a little.
=> added back button element

app/javascript/controllers/edit_event_controller.js, app/views/events/_event_modal.html.erb
added hobby icons to change in event edit form
=> Added Hobby icons on edit form

app/controllers/users/registrations_controller.rb, app/controllers/users/sessions_controller.rb, config/routes.rb
added a session controller and added some code to redirect to the profile when login, sign up or edit
=> fixed the path for edit/login

app/assets/stylesheets/components/_event_modal.scss, app/assets/stylesheets/components/_index.scss, app/views/events/_event_modal.html.erb
added some style and now hobby icon on the event modal
=> added some style for modal

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_event_card.scss, app/assets/stylesheets/components/_event_modal.scss, app/views/events/_attending.html.erb, app/views/events/_event_modal.html.erb, app/views/events/_interested.html.erb, app/views/events/index.html.erb, app/views/users/show.html.erb
added style to modal (icons for edit and delete action, attending list with avatar)
but you see lists like this:
still need to fix this
=> Added style to modal, Date-format, icons

app/assets/stylesheets/components/_event_modal.scss, app/views/events/_event_modal.html.erb
modal in center of screen 
closing icon in right-hand corner
title font looks the same as hobby-modal
=> event-modal looks good

app/assets/stylesheets/components/_event_modal.scss, app/views/events/_event_modal.html.erb
background color is now white and the closing icon has padding
=> event-modal background white

app/views/shared/_header.html.erb
added the homepage link to the logo in the header
=> homepage link added to the main logo

app/assets/stylesheets/components/_user_card.scss, app/views/users/index.html.erb
=> user-card clickable

app/controllers/users_controller.rb, app/views/chatrooms/index.html.erb, app/views/hobbies/index.html.erb
=> see all links are now directing properly

app/assets/stylesheets/components/_user_card.scss
class name in user-index of the div is fixed
=> class name in user-index of avatar changed

app/assets/stylesheets/components/_avatar.scss, app/controllers/events_controller.rb, app/views/hobbies/index.html.erb
=>  fixed search

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_hobby_card.scss, app/views/chatrooms/_new.html.erb, app/views/hobbies/index.html.erb
the sizing issue should be fixed
=> Avatar fix

app/assets/stylesheets/components/_chatroom.scss, app/views/messages/_message.html.erb
deleted name on messages and switched position of date and message-content.
=> chat messages look better

app/assets/stylesheets/components/_user_card.scss, app/views/users/show.html.erb
=> updated the users cards and profile page

app/helpers/meta_tags_helper.rb, app/models/event.rb, app/models/user.rb, app/views/chatrooms/_new.html.erb, app/views/events/_event_modal.html.erb, app/views/events/index.html.erb, app/views/users/show.html.erb
made the location display only city and country and added border around avatar
=> fix the location length and added border to avatar

app/assets/stylesheets/components/_chatroom.scss
=> adjusted chatroom index container so its scrollable

app/assets/stylesheets/components/_hobby_card.scss, app/views/hobbies/index.html.erb, app/views/hobbies/show.html.erb
changed padding on hobby-icons 
border under each event
avatar centered but on left side
date format userfriendly
=> hobby-cards and hobby-modal style fixing

app/assets/stylesheets/components/_hobby_card.scss, app/views/hobbies/index.html.erb
you see users without profile pic in hobby-modal
=> you see users without avatar in hobby-modal

app/assets/stylesheets/components/_buttons.scss, app/views/chatrooms/_new.html.erb
=> changed the confirm button

app/assets/stylesheets/components/_user_card.scss, app/views/hobbies/index.html.erb, app/views/users/show.html.erb
icons in two rows again
hobby-modal: link to all events and all fans only shows up if there are more than 5 fans and more than 3 events
=> icons in two rows

app/controllers/users_controller.rb
I've updated the search for users to be able to look for hobbies and username
=> changed the search for users

app/models/user.rb, app/views/pages/home.html.erb
Removed the login button from homepage
Limited characters for the username
=> removed btn login homepage and limit character on the username

app/views/hobbies/index.html.erb, app/views/users/show.html.erb
=> note if no events created/attended yet

public/404.html, public/500.html
404 and 500 error pages now done
=> resized ghost for error page

app/controllers/users_controller.rb, app/views/chatrooms/_new.html.erb, app/views/events/_event_modal.html.erb
Fixed the connection modal text displaying and the edit event location
=> fixed issues

app/controllers/events_controller.rb, public/404.html, public/500.html
so you can search by hobby name or event name
=> fixed search for events index 
